apiVersion: v1
kind: Service
metadata:
  name: {{ include "iot-edge-opc-plc.fullname" . }}
  labels:
    {{- include "iot-edge-opc-plc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.opcua.port }}
      targetPort: 50000
      protocol: TCP
      name: opcua
  selector:
    {{- include "iot-edge-opc-plc.selectorLabels" . | nindent 4 }}
