apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivemq-edge.fullname" . }}
  labels:
    {{- include "hivemq-edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    {{- include "hivemq-edge.selectorLabels" . | nindent 4 }}
