apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmusedge.fullname" . }}
  labels:
    {{- include "litmusedge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.litmusEdgeSolutions.mds.enabled }}
    - port: {{ .Values.litmusEdgeSolutions.mds.litmusEdgePort }}
      targetPort: {{ .Values.litmusEdgeSolutions.mds.litmusEdgePort }}
      protocol: TCP
      name: mdsInbound
    {{- end }}  
  selector: 
    {{- include "litmusedge.selectorLabels" . | nindent 4 }}
